apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proglog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proglog.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  serviceName: {{ include "proglog.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proglog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "proglog.fullname" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proglog.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ include "proglog.fullname" . }}--config-init
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: datadir
              mountPath: /var/run/proglog
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proglog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "proglog.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
          - name: rpc
            containerPort: {{ .Values.rpcPort }}
          - name: serf
            containerPort: {{ .Values.serfPort }}
#          args:
#            - --config-file=/var/run/proglog/config.yaml
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}" ]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}" ]
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessMode: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage }}